{{- if and .Values.serviceAccount.enabled .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: {{ .Release.Name }}
    labels:
      {{- include "service-deployment.labels" . | nindent 6 }}
    annotations:
      {{- include "service-deployment.resourceAnnotations" . | nindent 6 }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
