{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  annotations:
    {{- include "service-deployment.resourceAnnotations" . | nindent 4 }}
    {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    {{- include "service-deployment.labels" . | nindent 4 }}
{{- end -}}
