name: Application Local Kubernetes CI

on:
  pull_request:
    types:
      - synchronize
      - opened
    paths:
      - application/aws_ec2/src/**
      - application/aws_ec2/pom.xml
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Check aws ec2 flavour
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up JDK 17
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          overwrite-settings: false

      - name: Run fmt-plugin check goal
        working-directory: application/aws_ec2
        run: mvn --no-transfer-progress com.spotify.fmt:fmt-maven-plugin:2.20:check

      - name: Provide format fix instructions if check fails
        if: failure()
        run: |
          echo "::error::Formatting check failed. To fix formatting issues locally, run:"
          echo "mvn com.spotify.fmt:fmt-maven-plugin:2.20:format"

      - name: Tests
        working-directory: application/aws_ec2
        run: mvn --no-transfer-progress clean verify
